/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameMode = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'playerCount' : IDL.Nat,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const NewsPost = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'category' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'score' : IDL.Nat,
  'playerName' : IDL.Text,
});
export const ServerInfo = IDL.Record({
  'ip' : IDL.Text,
  'totalPlayers' : IDL.Nat,
  'onlinePlayers' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'maxPlayers' : IDL.Nat,
});
export const Stats = IDL.Record({
  'totalBlocksPlaced' : IDL.Nat,
  'uptimePercentage' : IDL.Float64,
  'totalKills' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addTotalPlayers' : IDL.Func([IDL.Nat], [], []),
  'getAllGameModes' : IDL.Func([], [IDL.Vec(GameMode)], ['query']),
  'getAllNews' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getServerInfo' : IDL.Func([], [ServerInfo], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'updateOnlinePlayerCount' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameMode = IDL.Record({
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'playerCount' : IDL.Nat,
    'description' : IDL.Text,
  });
  const Time = IDL.Int;
  const NewsPost = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'category' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'score' : IDL.Nat,
    'playerName' : IDL.Text,
  });
  const ServerInfo = IDL.Record({
    'ip' : IDL.Text,
    'totalPlayers' : IDL.Nat,
    'onlinePlayers' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'maxPlayers' : IDL.Nat,
  });
  const Stats = IDL.Record({
    'totalBlocksPlaced' : IDL.Nat,
    'uptimePercentage' : IDL.Float64,
    'totalKills' : IDL.Nat,
  });
  
  return IDL.Service({
    'addTotalPlayers' : IDL.Func([IDL.Nat], [], []),
    'getAllGameModes' : IDL.Func([], [IDL.Vec(GameMode)], ['query']),
    'getAllNews' : IDL.Func([], [IDL.Vec(NewsPost)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getServerInfo' : IDL.Func([], [ServerInfo], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'updateOnlinePlayerCount' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };