/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameMode {
  'icon' : string,
  'name' : string,
  'playerCount' : bigint,
  'description' : string,
}
export interface LeaderboardEntry { 'score' : bigint, 'playerName' : string }
export interface NewsPost {
  'title' : string,
  'content' : string,
  'date' : Time,
  'category' : string,
}
export interface ServerInfo {
  'ip' : string,
  'totalPlayers' : bigint,
  'onlinePlayers' : bigint,
  'name' : string,
  'description' : string,
  'maxPlayers' : bigint,
}
export interface Stats {
  'totalBlocksPlaced' : bigint,
  'uptimePercentage' : number,
  'totalKills' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addTotalPlayers' : ActorMethod<[bigint], undefined>,
  'getAllGameModes' : ActorMethod<[], Array<GameMode>>,
  'getAllNews' : ActorMethod<[], Array<NewsPost>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getServerInfo' : ActorMethod<[], ServerInfo>,
  'getStats' : ActorMethod<[], Stats>,
  'updateOnlinePlayerCount' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];